name: Release
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: lts/*

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release \
            --branches main \
            --plugins @semantic-release/github \
            --plugins @semantic-release/commit-analyzer \
            --plugins @semantic-release/release-notes-generator
